//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardIndex", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art188KP.
        /// </summary>
        internal static string Art188KP {
            get {
                return ResourceManager.GetString("Art188KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płaca zasadnicza.
        /// </summary>
        internal static string BaseSalary {
            get {
                return ResourceManager.GetString("BaseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współczynniki.
        /// </summary>
        internal static string Coefficient {
            get {
                return ResourceManager.GetString("Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składnik wynagrodzenia.
        /// </summary>
        internal static string ComponentRemunerationLabel {
            get {
                return ResourceManager.GetString("ComponentRemunerationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zawarcia umowy.
        /// </summary>
        internal static string DateAgreementLabel {
            get {
                return ResourceManager.GetString("DateAgreementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zwolnienia.
        /// </summary>
        internal static string DateDismissalLabel {
            get {
                return ResourceManager.GetString("DateDismissalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymiar etatu.
        /// </summary>
        internal static string DimensionTimeLabel {
            get {
                return ResourceManager.GetString("DimensionTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpośredni podwładni.
        /// </summary>
        internal static string DirectReports {
            get {
                return ResourceManager.GetString("DirectReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premia uznaniowa.
        /// </summary>
        internal static string DiscretionaryBonus {
            get {
                return ResourceManager.GetString("DiscretionaryBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data końca umowy.
        /// </summary>
        internal static string EndDateContractLabel {
            get {
                return ResourceManager.GetString("EndDateContractLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekwiwalent Urlopowy.
        /// </summary>
        internal static string EquivalentVacationLabel {
            get {
                return ResourceManager.GetString("EquivalentVacationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanse i umowy.
        /// </summary>
        internal static string FinanceAndContracts {
            get {
                return ResourceManager.GetString("FinanceAndContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop naliczony.
        /// </summary>
        internal static string HolidaysCalculated {
            get {
                return ResourceManager.GetString("HolidaysCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop należny.
        /// </summary>
        internal static string HolidaysDue {
            get {
                return ResourceManager.GetString("HolidaysDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop rehabilitacyjny.
        /// </summary>
        internal static string HolidaysRehabilitation {
            get {
                return ResourceManager.GetString("HolidaysRehabilitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop zaległy.
        /// </summary>
        internal static string HolidaysUnderpaid {
            get {
                return ResourceManager.GetString("HolidaysUnderpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykorzystano za rok bierzący.
        /// </summary>
        internal static string HolidaysUsed {
            get {
                return ResourceManager.GetString("HolidaysUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premia mistrza.
        /// </summary>
        internal static string MasterBonus {
            get {
                return ResourceManager.GetString("MasterBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badania lekarskie i uprawnienia.
        /// </summary>
        internal static string MedicalExaminationAndAuthorizations {
            get {
                return ResourceManager.GetString("MedicalExaminationAndAuthorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozostało do wykorzystania.
        /// </summary>
        internal static string RemainedUnused {
            get {
                return ResourceManager.GetString("RemainedUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynagrodzenie za okres bieżący.
        /// </summary>
        internal static string RemunerationCurrentPeriodLabel {
            get {
                return ResourceManager.GetString("RemunerationCurrentPeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport na dzień.
        /// </summary>
        internal static string ReportForDay {
            get {
                return ResourceManager.GetString("ReportForDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raportuje do.
        /// </summary>
        internal static string ReportsTo {
            get {
                return ResourceManager.GetString("ReportsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doradca handlowy.
        /// </summary>
        internal static string SalesAdvisorLabel {
            get {
                return ResourceManager.GetString("SalesAdvisorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura i Lokalizacja.
        /// </summary>
        internal static string StructureAndLocation {
            get {
                return ResourceManager.GetString("StructureAndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj umowy o pracę.
        /// </summary>
        internal static string TypeEmploymentContractLabel {
            get {
                return ResourceManager.GetString("TypeEmploymentContractLabel", resourceCulture);
            }
        }
    }
}
