//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępy.
        /// </summary>
        internal static string Accesses {
            get {
                return ResourceManager.GetString("Accesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatki.
        /// </summary>
        internal static string Additions {
            get {
                return ResourceManager.GetString("Additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres zamieszkania.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres do korespondencji.
        /// </summary>
        internal static string AddressForCorrespondenceLabel {
            get {
                return ResourceManager.GetString("AddressForCorrespondenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota składki (PLN).
        /// </summary>
        internal static string AmountContribution {
            get {
                return ResourceManager.GetString("AmountContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota przyznana.
        /// </summary>
        internal static string AmountGrantedLabel {
            get {
                return ResourceManager.GetString("AmountGrantedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        internal static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacje.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiwum.
        /// </summary>
        internal static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obszar.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe informacje.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płaca zasadnicza.
        /// </summary>
        internal static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książka.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddział.
        /// </summary>
        internal static string BranchLabel {
            get {
                return ResourceManager.GetString("BranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współczynnik.
        /// </summary>
        internal static string Coefficient {
            get {
                return ResourceManager.GetString("Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmina.
        /// </summary>
        internal static string CommunityLabel {
            get {
                return ResourceManager.GetString("CommunityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane kontaktowe.
        /// </summary>
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer umowy.
        /// </summary>
        internal static string ContractNumberLabel {
            get {
                return ResourceManager.GetString("ContractNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umowy.
        /// </summary>
        internal static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współpracownicy.
        /// </summary>
        internal static string Coworkers {
            get {
                return ResourceManager.GetString("Coworkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrącenia.
        /// </summary>
        internal static string Deductions {
            get {
                return ResourceManager.GetString("Deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dział.
        /// </summary>
        internal static string DepartmentLabel {
            get {
                return ResourceManager.GetString("DepartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpośredni przełożony.
        /// </summary>
        internal static string DirectSupervisorLabel {
            get {
                return ResourceManager.GetString("DirectSupervisorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepełnosprawność.
        /// </summary>
        internal static string DisabilityLabel {
            get {
                return ResourceManager.GetString("DisabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenty.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykształcenie.
        /// </summary>
        internal static string EducationLabel {
            get {
                return ResourceManager.GetString("EducationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer pracownika.
        /// </summary>
        internal static string EmployeeNumberLabel {
            get {
                return ResourceManager.GetString("EmployeeNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownicy.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uprawnienie.
        /// </summary>
        internal static string Entitlement {
            get {
                return ResourceManager.GetString("Entitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas przetwarzania Twojego żądania..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer błędu.
        /// </summary>
        internal static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd dla programisty.
        /// </summary>
        internal static string ErrorProgrammer {
            get {
                return ResourceManager.GetString("ErrorProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wygaśnięcia.
        /// </summary>
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanse.
        /// </summary>
        internal static string Finances {
            get {
                return ResourceManager.GetString("Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imie.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rozpoczęcia.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop należny.
        /// </summary>
        internal static string HolidaysDue {
            get {
                return ResourceManager.GetString("HolidaysDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string Lack {
            get {
                return ResourceManager.GetString("Lack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak uprawnień.
        /// </summary>
        internal static string LackPermissions {
            get {
                return ResourceManager.GetString("LackPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyrektor oddziału.
        /// </summary>
        internal static string ManagerOfBranchLabel {
            get {
                return ResourceManager.GetString("ManagerOfBranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badania lekarskie.
        /// </summary>
        internal static string MedicalExamination {
            get {
                return ResourceManager.GetString("MedicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz uprawnień do przeglądania tego zasobu..
        /// </summary>
        internal static string Message401 {
            get {
                return ResourceManager.GetString("Message401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostęp do żądanej strony został zabroniony..
        /// </summary>
        internal static string Message403 {
            get {
                return ResourceManager.GetString("Message403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żądana strona nie została znaleziona..
        /// </summary>
        internal static string Message404 {
            get {
                return ResourceManager.GetString("Message404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon komórkowy.
        /// </summary>
        internal static string MobileNumberLabel {
            get {
                return ResourceManager.GetString("MobileNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mój portal.
        /// </summary>
        internal static string MyPortal {
            get {
                return ResourceManager.GetString("MyPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr konta bankowego.
        /// </summary>
        internal static string NoBankAccountLabel {
            get {
                return ResourceManager.GetString("NoBankAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komórka organizacyjna.
        /// </summary>
        internal static string OrganizationalCellLabel {
            get {
                return ResourceManager.GetString("OrganizationalCellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka organizacyjna.
        /// </summary>
        internal static string OrganizationalUnitLabel {
            get {
                return ResourceManager.GetString("OrganizationalUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane osobiste.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesel.
        /// </summary>
        internal static string PeselLabel {
            get {
                return ResourceManager.GetString("PeselLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPK.
        /// </summary>
        internal static string PlaceWhereCostsAriseLabel {
            get {
                return ResourceManager.GetString("PlaceWhereCostsAriseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanowisko.
        /// </summary>
        internal static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Pocztowy.
        /// </summary>
        internal static string PostalCodeLabel {
            get {
                return ResourceManager.GetString("PostalCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokal.
        /// </summary>
        internal static string PremisesLabel {
            get {
                return ResourceManager.GetString("PremisesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przekrój produktowy.
        /// </summary>
        internal static string ProductSectionLabel {
            get {
                return ResourceManager.GetString("ProductSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres zameldowania.
        /// </summary>
        internal static string RegisteredAddressLabel {
            get {
                return ResourceManager.GetString("RegisteredAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. rejestracyjny.
        /// </summary>
        internal static string RegistrationNumberLabel {
            get {
                return ResourceManager.GetString("RegistrationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzuć.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamiętaj mnie?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnioski.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywróć.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomieszczenie.
        /// </summary>
        internal static string RoomLabel {
            get {
                return ResourceManager.GetString("RoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj.
        /// </summary>
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki wyszukania.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pion.
        /// </summary>
        internal static string SectionLabel {
            get {
                return ResourceManager.GetString("SectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silos.
        /// </summary>
        internal static string Silo {
            get {
                return ResourceManager.GetString("Silo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość.
        /// </summary>
        internal static string SpotLabel {
            get {
                return ResourceManager.GetString("SpotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        internal static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica nr.
        /// </summary>
        internal static string StreetNoLabel {
            get {
                return ResourceManager.GetString("StreetNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis się powiódł.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko i imię.
        /// </summary>
        internal static string SurnameName {
            get {
                return ResourceManager.GetString("SurnameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 Nieautoryzowany dostęp.
        /// </summary>
        internal static string Title401 {
            get {
                return ResourceManager.GetString("Title401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 Zabroniony.
        /// </summary>
        internal static string Title403 {
            get {
                return ResourceManager.GetString("Title403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Nie znaleziono.
        /// </summary>
        internal static string Title404 {
            get {
                return ResourceManager.GetString("Title404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlopy.
        /// </summary>
        internal static string Urlopy {
            get {
                return ResourceManager.GetString("Urlopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika lub hasło jest niepoprawne.
        /// </summary>
        internal static string UserNamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce pracy.
        /// </summary>
        internal static string WorkplaceLabel {
            get {
                return ResourceManager.GetString("WorkplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakład.
        /// </summary>
        internal static string WorksLabel {
            get {
                return ResourceManager.GetString("WorksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania.
        /// </summary>
        internal static string Zadania {
            get {
                return ResourceManager.GetString("Zadania", resourceCulture);
            }
        }
    }
}
