//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj pracownika do ubezpieczenia.
        /// </summary>
        internal static string AddEmployeeInsurance {
            get {
                return ResourceManager.GetString("AddEmployeeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przydział domyślny.
        /// </summary>
        internal static string AllocationDefault {
            get {
                return ResourceManager.GetString("AllocationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współczynniki.
        /// </summary>
        internal static string Coefficients {
            get {
                return ResourceManager.GetString("Coefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sam. Słuzbowy.
        /// </summary>
        internal static string CompanyCar {
            get {
                return ResourceManager.GetString("CompanyCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data pierwszego potrącenia.
        /// </summary>
        internal static string DateFirstDeduction {
            get {
                return ResourceManager.GetString("DateFirstDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ostatniego potrącenia.
        /// </summary>
        internal static string DateLastDeduction {
            get {
                return ResourceManager.GetString("DateLastDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza rata kapitału.
        /// </summary>
        internal static string FirstInstallmentCapitalLabel {
            get {
                return ResourceManager.GetString("FirstInstallmentCapitalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza rata odsetki.
        /// </summary>
        internal static string FirstInstallmentInterestLabel {
            get {
                return ResourceManager.GetString("FirstInstallmentInterestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hestia.
        /// </summary>
        internal static string Hestia {
            get {
                return ResourceManager.GetString("Hestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pożyczki inne.
        /// </summary>
        internal static string LoansOther {
            get {
                return ResourceManager.GetString("LoansOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opieka medyczna.
        /// </summary>
        internal static string MedicalCare {
            get {
                return ResourceManager.GetString("MedicalCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rata cykliczna.
        /// </summary>
        internal static string MonthlyCycleLabel {
            get {
                return ResourceManager.GetString("MonthlyCycleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multisport.
        /// </summary>
        internal static string Multisport {
            get {
                return ResourceManager.GetString("Multisport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polisy PZU.
        /// </summary>
        internal static string PZUInsurance {
            get {
                return ResourceManager.GetString("PZUInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport potrąceń.
        /// </summary>
        internal static string ReportDeductionsLabel {
            get {
                return ResourceManager.GetString("ReportDeductionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura i lokalizacja.
        /// </summary>
        internal static string StructureAndLocation {
            get {
                return ResourceManager.GetString("StructureAndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZFŚS.
        /// </summary>
        internal static string ZFSS {
            get {
                return ResourceManager.GetString("ZFSS", resourceCulture);
            }
        }
    }
}
