//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.Basic.Presentation.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workflow.Basic.Presentation.Resources.Common.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępy.
        /// </summary>
        public static string Accesses {
            get {
                return ResourceManager.GetString("Accesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatki.
        /// </summary>
        public static string Additions {
            get {
                return ResourceManager.GetString("Additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres zamieszkania.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres do korespondencji.
        /// </summary>
        public static string AddressForCorrespondenceLabel {
            get {
                return ResourceManager.GetString("AddressForCorrespondenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota składki (PLN).
        /// </summary>
        public static string AmountContribution {
            get {
                return ResourceManager.GetString("AmountContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota przyznana.
        /// </summary>
        public static string AmountGrantedLabel {
            get {
                return ResourceManager.GetString("AmountGrantedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacje.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiwum.
        /// </summary>
        public static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obszar.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe informacje.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płaca zasadnicza.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książka.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddział.
        /// </summary>
        public static string BranchLabel {
            get {
                return ResourceManager.GetString("BranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współczynnik.
        /// </summary>
        public static string Coefficient {
            get {
                return ResourceManager.GetString("Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmina.
        /// </summary>
        public static string CommunityLabel {
            get {
                return ResourceManager.GetString("CommunityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane kontaktowe.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer umowy.
        /// </summary>
        public static string ContractNumberLabel {
            get {
                return ResourceManager.GetString("ContractNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umowy.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współpracownicy.
        /// </summary>
        public static string Coworkers {
            get {
                return ResourceManager.GetString("Coworkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrącenia.
        /// </summary>
        public static string Deductions {
            get {
                return ResourceManager.GetString("Deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dział.
        /// </summary>
        public static string DepartmentLabel {
            get {
                return ResourceManager.GetString("DepartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpośredni przełożony.
        /// </summary>
        public static string DirectSupervisorLabel {
            get {
                return ResourceManager.GetString("DirectSupervisorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepełnosprawność.
        /// </summary>
        public static string DisabilityLabel {
            get {
                return ResourceManager.GetString("DisabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenty.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykształcenie.
        /// </summary>
        public static string EducationLabel {
            get {
                return ResourceManager.GetString("EducationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer pracownika.
        /// </summary>
        public static string EmployeeNumberLabel {
            get {
                return ResourceManager.GetString("EmployeeNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownicy.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uprawnienie.
        /// </summary>
        public static string Entitlement {
            get {
                return ResourceManager.GetString("Entitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas przetwarzania Twojego żądania..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer błędu.
        /// </summary>
        public static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd dla programisty.
        /// </summary>
        public static string ErrorProgrammer {
            get {
                return ResourceManager.GetString("ErrorProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wygaśnięcia.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanse.
        /// </summary>
        public static string Finances {
            get {
                return ResourceManager.GetString("Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imie.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rozpoczęcia.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop należny.
        /// </summary>
        public static string HolidaysDue {
            get {
                return ResourceManager.GetString("HolidaysDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        public static string Lack {
            get {
                return ResourceManager.GetString("Lack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak uprawnień.
        /// </summary>
        public static string LackPermissions {
            get {
                return ResourceManager.GetString("LackPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyrektor oddziału.
        /// </summary>
        public static string ManagerOfBranchLabel {
            get {
                return ResourceManager.GetString("ManagerOfBranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badania lekarskie.
        /// </summary>
        public static string MedicalExamination {
            get {
                return ResourceManager.GetString("MedicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz uprawnień do przeglądania tego zasobu..
        /// </summary>
        public static string Message401 {
            get {
                return ResourceManager.GetString("Message401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostęp do żądanej strony został zabroniony..
        /// </summary>
        public static string Message403 {
            get {
                return ResourceManager.GetString("Message403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żądana strona nie została znaleziona..
        /// </summary>
        public static string Message404 {
            get {
                return ResourceManager.GetString("Message404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon komórkowy.
        /// </summary>
        public static string MobileNumberLabel {
            get {
                return ResourceManager.GetString("MobileNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mój portal.
        /// </summary>
        public static string MyPortal {
            get {
                return ResourceManager.GetString("MyPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr..
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr konta bankowego.
        /// </summary>
        public static string NoBankAccountLabel {
            get {
                return ResourceManager.GetString("NoBankAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komórka organizacyjna.
        /// </summary>
        public static string OrganizationalCellLabel {
            get {
                return ResourceManager.GetString("OrganizationalCellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka organizacyjna.
        /// </summary>
        public static string OrganizationalUnitLabel {
            get {
                return ResourceManager.GetString("OrganizationalUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane osobiste.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesel.
        /// </summary>
        public static string PeselLabel {
            get {
                return ResourceManager.GetString("PeselLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPK.
        /// </summary>
        public static string PlaceWhereCostsAriseLabel {
            get {
                return ResourceManager.GetString("PlaceWhereCostsAriseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanowisko.
        /// </summary>
        public static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Pocztowy.
        /// </summary>
        public static string PostalCodeLabel {
            get {
                return ResourceManager.GetString("PostalCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokal.
        /// </summary>
        public static string PremisesLabel {
            get {
                return ResourceManager.GetString("PremisesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przekrój produktowy.
        /// </summary>
        public static string ProductSectionLabel {
            get {
                return ResourceManager.GetString("ProductSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres zameldowania.
        /// </summary>
        public static string RegisteredAddressLabel {
            get {
                return ResourceManager.GetString("RegisteredAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. rejestracyjny.
        /// </summary>
        public static string RegistrationNumberLabel {
            get {
                return ResourceManager.GetString("RegistrationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzuć.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamiętaj mnie?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnioski.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywróć.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomieszczenie.
        /// </summary>
        public static string RoomLabel {
            get {
                return ResourceManager.GetString("RoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki wyszukania.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pion.
        /// </summary>
        public static string SectionLabel {
            get {
                return ResourceManager.GetString("SectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silos.
        /// </summary>
        public static string Silo {
            get {
                return ResourceManager.GetString("Silo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość.
        /// </summary>
        public static string SpotLabel {
            get {
                return ResourceManager.GetString("SpotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica nr.
        /// </summary>
        public static string StreetNoLabel {
            get {
                return ResourceManager.GetString("StreetNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis się powiódł.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko i imię.
        /// </summary>
        public static string SurnameName {
            get {
                return ResourceManager.GetString("SurnameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 Nieautoryzowany dostęp.
        /// </summary>
        public static string Title401 {
            get {
                return ResourceManager.GetString("Title401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 Zabroniony.
        /// </summary>
        public static string Title403 {
            get {
                return ResourceManager.GetString("Title403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Nie znaleziono.
        /// </summary>
        public static string Title404 {
            get {
                return ResourceManager.GetString("Title404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop.
        /// </summary>
        public static string Urlop {
            get {
                return ResourceManager.GetString("Urlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlopy.
        /// </summary>
        public static string Urlopy {
            get {
                return ResourceManager.GetString("Urlopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika lub hasło jest niepoprawne.
        /// </summary>
        public static string UserNamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce pracy.
        /// </summary>
        public static string WorkplaceLabel {
            get {
                return ResourceManager.GetString("WorkplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakład.
        /// </summary>
        public static string WorksLabel {
            get {
                return ResourceManager.GetString("WorksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania.
        /// </summary>
        public static string Zadania {
            get {
                return ResourceManager.GetString("Zadania", resourceCulture);
            }
        }
    }
}
